[package]
name = "chess-player"
version = "0.1.0"
authors = ["benjazzy <benjazzy64@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.1.1"
dialoguer = "0.7.1"
threadpool = "1.8.1"